// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Refeicao.Core.Database.Context;

#nullable disable

namespace Refeicao.Core.Migrations
{
    [DbContext(typeof(RefeicaoContext))]
    [Migration("20260910154912_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Refeicao.Core.Database.Entities.Acompanhamento", b =>
                {
                    b.Property<int>("IdAcompanhamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_ACOMPANHAMENTO");

                    b.Property<string>("DsAcompanhamento")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DS_ACOMPANHAMENTO");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("IdUsuarioDeletou")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ID_USUARIO_DELETOU");

                    b.Property<bool>("SnDeletado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("SN_DELETADO");

                    b.HasKey("IdAcompanhamento");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdUsuarioDeletou");

                    b.ToTable("ACOMPANHAMENTO", (string)null);
                });

            modelBuilder.Entity("Refeicao.Core.Database.Entities.AcompanhamentoRefeicao", b =>
                {
                    b.Property<int>("IdAcompanhamento")
                        .HasColumnType("int")
                        .HasColumnName("ID_ACOMPANHAMENTO");

                    b.Property<int>("IdRefeicao")
                        .HasColumnType("int")
                        .HasColumnName("ID_REFEICAO");

                    b.HasKey("IdAcompanhamento", "IdRefeicao");

                    b.HasIndex("IdRefeicao");

                    b.ToTable("ACOMPANHAMENTO_REFEICAO", (string)null);
                });

            modelBuilder.Entity("Refeicao.Core.Database.Entities.Cardapio", b =>
                {
                    b.Property<int>("IdCardapio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_CARDAPIO");

                    b.Property<DateOnly>("DtCardapio")
                        .HasColumnType("date")
                        .HasColumnName("DT_CARDAPIO");

                    b.Property<int>("IdRefeicao")
                        .HasColumnType("int")
                        .HasColumnName("ID_REFEICAO");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<bool>("SnFechado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("SN_FECHADO");

                    b.Property<string>("TpCardapio")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("TP_CARDAPIO");

                    b.HasKey("IdCardapio");

                    b.HasIndex("IdRefeicao");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("DtCardapio", "TpCardapio")
                        .IsUnique();

                    b.ToTable("CARDAPIO", (string)null);
                });

            modelBuilder.Entity("Refeicao.Core.Database.Entities.Funcionario", b =>
                {
                    b.Property<int>("IdFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_FUNCIONARIO");

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DT_CADASTRO");

                    b.Property<DateTime?>("DtInativacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DT_INATIVACAO");

                    b.Property<string>("HashSenha")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("HASH_SENHA");

                    b.Property<string>("NmUsuario")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("NM_USUARIO");

                    b.Property<bool>("PrimeiroAcesso")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("SN_PRIMEIRO_ACESSO");

                    b.HasKey("IdFuncionario");

                    b.ToTable("FUNCIONARIO", (string)null);
                });

            modelBuilder.Entity("Refeicao.Core.Database.Entities.FuncionarioCardapio", b =>
                {
                    b.Property<int>("IdFuncionario")
                        .HasColumnType("int")
                        .HasColumnName("ID_FUNCIONARIO");

                    b.Property<int>("IdCardapio")
                        .HasColumnType("int")
                        .HasColumnName("ID_CARDAPIO");

                    b.Property<DateTime>("DtConfirmacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DT_CONFIRMACAO");

                    b.HasKey("IdFuncionario", "IdCardapio");

                    b.HasIndex("IdCardapio");

                    b.ToTable("FUNCIONARIO_CARDAPIO", (string)null);
                });

            modelBuilder.Entity("Refeicao.Core.Database.Entities.Refeicao", b =>
                {
                    b.Property<int>("IdRefeicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_REFEICAO");

                    b.Property<string>("DsRefeicao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DS_REFEICAO");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("IdRefeicao");

                    b.HasIndex("IdUsuario");

                    b.ToTable("REFEICAO", (string)null);
                });

            modelBuilder.Entity("Refeicao.Core.Database.Entities.Usuario", b =>
                {
                    b.Property<string>("IdUsuario")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DT_CADASTRO");

                    b.Property<DateTime?>("DtInativacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DT_INATIVACAO");

                    b.Property<string>("HashSenha")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("HASH_SENHA");

                    b.Property<string>("NmUsuario")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("NM_USUARIO");

                    b.Property<bool>("PrimeiroAcesso")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("SN_PRIMEIRO_ACESSO");

                    b.HasKey("IdUsuario");

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("Refeicao.Core.Database.Entities.Acompanhamento", b =>
                {
                    b.HasOne("Refeicao.Core.Database.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Refeicao.Core.Database.Entities.Usuario", "UsuarioDeletou")
                        .WithMany()
                        .HasForeignKey("IdUsuarioDeletou")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioDeletou");
                });

            modelBuilder.Entity("Refeicao.Core.Database.Entities.AcompanhamentoRefeicao", b =>
                {
                    b.HasOne("Refeicao.Core.Database.Entities.Acompanhamento", "Acompanhamento")
                        .WithMany("AcompanhamentosRefeicao")
                        .HasForeignKey("IdAcompanhamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Refeicao.Core.Database.Entities.Refeicao", "Refeicao")
                        .WithMany("AcompanhamentosRefeicao")
                        .HasForeignKey("IdRefeicao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acompanhamento");

                    b.Navigation("Refeicao");
                });

            modelBuilder.Entity("Refeicao.Core.Database.Entities.Cardapio", b =>
                {
                    b.HasOne("Refeicao.Core.Database.Entities.Refeicao", "Refeicao")
                        .WithMany("Cardapios")
                        .HasForeignKey("IdRefeicao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Refeicao.Core.Database.Entities.Usuario", "Usuario")
                        .WithMany("Cardapios")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Refeicao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Refeicao.Core.Database.Entities.FuncionarioCardapio", b =>
                {
                    b.HasOne("Refeicao.Core.Database.Entities.Cardapio", "Cardapio")
                        .WithMany("FuncionarioCardapios")
                        .HasForeignKey("IdCardapio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Refeicao.Core.Database.Entities.Funcionario", "Funcionario")
                        .WithMany("FuncionarioCardapios")
                        .HasForeignKey("IdFuncionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cardapio");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("Refeicao.Core.Database.Entities.Refeicao", b =>
                {
                    b.HasOne("Refeicao.Core.Database.Entities.Usuario", "Usuario")
                        .WithMany("Refeicoes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Refeicao.Core.Database.Entities.Acompanhamento", b =>
                {
                    b.Navigation("AcompanhamentosRefeicao");
                });

            modelBuilder.Entity("Refeicao.Core.Database.Entities.Cardapio", b =>
                {
                    b.Navigation("FuncionarioCardapios");
                });

            modelBuilder.Entity("Refeicao.Core.Database.Entities.Funcionario", b =>
                {
                    b.Navigation("FuncionarioCardapios");
                });

            modelBuilder.Entity("Refeicao.Core.Database.Entities.Refeicao", b =>
                {
                    b.Navigation("AcompanhamentosRefeicao");

                    b.Navigation("Cardapios");
                });

            modelBuilder.Entity("Refeicao.Core.Database.Entities.Usuario", b =>
                {
                    b.Navigation("Cardapios");

                    b.Navigation("Refeicoes");
                });
#pragma warning restore 612, 618
        }
    }
}
